### ISSUE TITLE
Nested (non-array) Objects

### ISSUE THREAD

**Issue by mhays118** [lukeredpath/swift-coding#3]
Hello, 

First off, I really like the idea of you created here. The tight coupling between `Codable` and a given model has been a pain point for me for a long time and I think this might be the solution I've been looking for.

I watched the NSScreencast series on this library and started playing around with it to evaluate if this could be a good fit for some of the codebases I am working on.

When messing around, I ran into an issue that I don't seem to see covered in either the series or the unit tests. 

There doesn't seem to be a good way to decode a nested object. The library does support decoding arrays of nested objects, but not single ones.

So I have the two following models that I quickly made for testing:
```swift
public struct User: Equatable {
    public let id: String
    public let name: PersonNameComponents
    public let address: Address?

    public init(
        id: String,
        name: PersonNameComponents,
        address: Address? = nil
    ) {
        self.id = id
        self.name = name
        self.address = address
    }
}

public struct Address: Equatable {
    public let street: String
    public let city: String
    public let state: String
    public let zipCode: Int

    public init(
        street: String,
        city: String,
        state: String,
        zipCode: Int
    ) {
        self.street = street
        self.city = city
        self.state = state
        self.zipCode = zipCode
    }
}
```

> Note that I am using a public init as I am planning to make these live in a separate library than the encoding/decoding.

Then I currently have the following for `Decoding` support for `User`:
```swift
extension User {
    enum CodingKeys: String, CodingKey {
        case id
        case firstName = "first_name"
        case lastName = "last_name"
        case address
    }
}

extension Decoding where Value == User {
    static var id: Decoding<String> = Decoding<String>
        .withKey(User.CodingKeys.id)

    static var name: Decoding<PersonNameComponents> {
        // Maps json with `first_name` and `last_name` properties into a ``PersonNameComponents`` object for ``Domain/User``
        .init { decoder in
            let container = try decoder.container(keyedBy: User.CodingKeys.self)
            let firstName = try container.decode(String.self, forKey: .firstName)
            let lastName = try container.decode(String.self, forKey: .lastName)

            var nameComponents = PersonNameComponents()
            nameComponents.givenName = firstName
            nameComponents.familyName = lastName
            return nameComponents
        }
    }

    // ⚠️ This does NOT work
    // It will try pulling all the properties on Address directly on to `User` instead of having
    // a nested object.
    //
    // Also cannot do `.withKey(User.CodingKeys.address)` afterwards,
    // as `Address` does NOT conform to `Decodable`
    static var address: Decoding<Address> = .standard

    /// Standard way of decoding a user
    static let compressed = zip(id, name).map { User.init(id: $0, name: $1) }
    static let standard = zip(id, name, address).map(User.init)
}
```

And `Address':
```swift
extension Address {
    enum CodingKeys: String, CodingKey {
        case street
        case city
        case state
        case zipCode = "zip"
    }
}

extension Decoding where Value == Address {
    static var street: Decoding<String> = Decoding<String>
        .withKey(Address.CodingKeys.street)

    static var city: Decoding<String> = Decoding<String>
        .withKey(Address.CodingKeys.city)

    static var state: Decoding<String> = Decoding<String>
        .withKey(Address.CodingKeys.state)

    static var zipCode: Decoding<Int> = Decoding<String>
        .withKey(Address.CodingKeys.zipCode)
        .map(Int.init)
        .replaceNil(with: 0)

    static var standard: Decoding<Address> {
        zip(with: Address.init)(street, city, state, zipCode)
    }
}
```

I then have a simple test:
```swift
let userJson = """
{
    "id": "1234",
    "first_name": "John",
    "last_name": "Smith",
    "address": {
        "street": "123 W Main Street",
        "city": "New York",
        "state": "NY",
        "zip": "00000"
    },
    "twitter_handle": "jsmith123"
}
""".data(using: .utf8)!

final class UserDecodingTests: XCTestCase {
    func test_user_decodes_successfully() throws {
        let decoder = JSONDecoder()
        let user: User = try decoder.decode(userJson, as: .standard)
        
        var name = PersonNameComponents()
        name.givenName = "John"
        name.familyName = "Smith"
        XCTAssertEqual(user, User(id: "1234", name: name))
    }
}

```

On the line `let user: User = try decoder.decode(userJson, as: .standard)`, I get this error:
```
caught error: "keyNotFound(CodingKeys(stringValue: "street", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"street\", intValue: nil) (\"street\").", underlyingError: nil))"
```
This appears to be happening since it is trying to use all the decoding properties I declared on `Decoding<Address>`, such as `.street` directly on User, but those keys obviously do not exist.

Please let me know if I am missing something. 

Thanks for your help and making this library.

Best,
Marcus

**Comment by lukeredpath** [comment]
@mhays118 thanks for checking out the library. I just added some test cases for your scenario and it worked fine:

https://github.com/lukeredpath/swift-coding/commit/38860e6255f448b7c6b2e053c0b8fbb679a0aa83

What you're missing here is that if you need to use an existing decoding for a type in the context of some parent type, you need to convert that decoding into a keyed decoding in the same way that you would for the basic decoding types, so where you are doing this:

```swift
static var address: Decoding<Address> = .standard
```

You actually need to use the `.withKey` or in your case, the `.optionalWithKey` modifier:

```swift
static var address: Decoding<Address?> = Decoding<Address>
    .standard
    .optionalWithKey(User.CodingKeys.address)
```

Neither of these methods require that your type conform to `Decodable` - they are defined on an unconstrained extension of `Decoding`. You do need to define your user address decoding as a decoding of `Decoding<Address?>` though because your `User` address property is optional.

**Comment by mhays118** [comment]
Hi @lukeredpath,

Thanks for getting back to me on this. I initially tried doing what you recommended, however, that was invalid. 

It looks like what is happening is that version I pulled into my project is version `0.0.1`, which is missing 04292296d55b00873354afd7b09e3d7c392b9e54, which adds support for using `optionalWithKey` and `withKey` on non-Decodable types. I'll switch to directly targeting the correct commit in SPM. 

Thanks for your help!

**Comment by lukeredpath** [comment]
@mhays118 thanks for pointing this out, I've just tagged a 0.0.2 release.
